name: JUCE VST3 Build

on:
  push:
    branches: [ "main", "test" ]
  pull_request:
    branches: [ "main", "test" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S . -G "Visual Studio 17 2022" -A x64

    - name: Build VST3
      run: cmake --build build --config Release --target CrokyScopy_VST3

    - name: Upload VST3
      uses: actions/upload-artifact@v4
      with:
        name: CrokyScopy-VST3
        path: build/CrokyScopy_artefacts/Release/VST3/CrokyScopy.vst3
